---
- name: "Install pip3 to manage python packages"
  package:
    name: "python3-pip"
    state: "present"
  when: "ansible_python_version is version_compare('3.0.0', '>=')"

- name: "Install pip to manage python packages"
  package:
    name: "python-pip"
    state: "present"
  when: "ansible_python_version is version_compare('3.0.0', '<=')"

- name: "Install the passlib python library"
  pip:
    name: "passlib"
    state: "latest"
